spring:
  datasource:
    username: root
    password: root
    url: jdbc:h2:./data/data;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
  main:
    lazy-initialization: true
app:
  jwt-secret-key: 3jlpWLEUjJtiv3u7gcgCm6HixXCBNK2r
