server:
  port: 9887
spring:
  application:
    name: thin-wiki
  r2dbc:
    username: root
    password:
    url: r2dbc:mysql://localhost:3306/thin-wiki?useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true

logging:
  level:
    wiki.thin: debug
  file:
    path: logs/
    name: thin-wiki.log
