spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/thin-wiki?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#  main:
#    lazy-initialization: true


app:
  jwt-secret-key: 3jlpWLEUjJtiv3u7gcgCm6HixXCBNK2r
logging:
  level:
    wiki.thin: debug
