server:
  port: 9887
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,application/font-woff
  undertow:
    threads:
      io: 1

spring:
  application:
    name: thin-wiki
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    url: jdbc:mysql://localhost:3306/thin-wiki?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    suffix: .ftlh
    template-loader-path:
      - file:./theme/
      - classpath:/templates/theme/
#  web:
#    resources:
#      static-locations:
#        - classpath:/templates/
#        - file:./theme/
  flyway:
    enabled: true
    clean-disabled: true
    locations:
      - classpath:db/migration
    table: schemas_version
    baseline-version: 1
    validate-on-migrate: true
    check-location: true
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wiki.thin.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-handlers-package: wiki.thin.common.mybatis.convert

logging:
  level:
    wiki.thin: debug
  file:
    path: logs/
    name: wiki.log

javamelody:
  enabled: true
  init-parameters:
    log: true
    monitoring-path: /admin/performance
    authorized-users: thinwiki:thinwiki
    rum-enabled: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #    url-exclude-pattern: (.*\.css|.*\.js|.*\.map)
    # to aggregate digits in http requests:
    http-transform-pattern: \d+
#  management-endpoint-monitoring-enabled: true
#app:
#  backup:
#    # 自动备份策略
#    strategies[0]:
#      modify-count: 1
#      duration: 1
#      time-unit: DAYS
#    strategies[1]:
#      modify-count: 10
#      duration: 12
#      time-unit: HOURS

