[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="sysVar" type="wiki.thin.theme.ftlh.variable.SystemVar" --]
[#-- @ftlvariable name="articleColumnVar" type="wiki.thin.theme.ftlh.variable.ArticleColumnVariable" --]
[#-- @ftlvariable name="navVar" type="wiki.thin.theme.ftlh.variable.NavVariable" --]
[#-- @ftlvariable name="secVar" type="wiki.thin.theme.ftlh.variable.SecurityVariable" --]
[#-- @ftlvariable name="articleVar" type="wiki.thin.theme.ftlh.variable.ArticleVariable" --]
[#-- @ftlvariable name="columnVar" type="wiki.thin.theme.ftlh.variable.ColumnVariable" --]
[#-- @ftlvariable name="resVar" type="wiki.thin.theme.ftlh.variable.ResourceVariable" --]
[#-- @ftlvariable name="version" type="java.lang.String" --]
[#-- @ftlvariable name="columnPath" type="java.lang.String" --]
[#-- @ftlvariable name="articleId" type="java.lang.Long" --]
[#-- @ftlvariable name="theme" type="wiki.thin.theme.ThemeManager" --]

[#-- @ftlvariable name="article" type="wiki.thin.entity.Article" --]
[#-- @ftlvariable name="storage" type="wiki.thin.entity.Storage" --]
[#-- @ftlvariable name="localStorage" type="wiki.thin.entity.LocalStorage" --]
[#-- @ftlvariable name="localStorages" type="java.util.List<wiki.thin.entity.LocalStorage>" --]
[#-- @ftlvariable name="githubStorage" type="wiki.thin.entity.GithubStorage" --]
[#-- @ftlvariable name="githubStorages" type="java.util.List<wiki.thin.entity.GithubStorage>" --]
[#-- @ftlvariable name="giteeStorage" type="wiki.thin.entity.GiteeStorage" --]
[#-- @ftlvariable name="giteeStorages" type="java.util.List<wiki.thin.entity.GiteeStorage>" --]
[#-- @ftlvariable name="storageVO" type="wiki.thin.web.vo.StorageVO" --]
[#-- @ftlvariable name="storageVOS" type="java.util.List<thin.web.vo.StorageVO>" --]
[#-- @ftlroot "" --]
