spring:
  datasource:
    username: dbuser
    password: dbpass
    url: jdbc:mysql://localhost:3306/thin-wiki?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
logging:
  level:
    wiki.thin: debug
javamelody:
  init-parameters:
    authorized-users: thinwiki:thinwiki # 监控账号密码 user:pass