name: Auto Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/thin-*.tar.gz,target/thin-wiki.jar"
          bodyFile: "release.md"
          token: ${{ secrets.TOKEN }}
