name: Auto Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true -Pmysql

      - name: Release
          uses: qcastel/github-actions-maven-release@master
          with:
            release-branch-name: "master"
            git-release-bot-name: "release-bot"
            git-release-bot-email: "release-bot@thin.wiki"
            maven-args: "-Plib -Dmaven.javadoc.skip=true -DskipTests"
            access-token: ${{ secrets.TOKEN }}
    
